export const landingCopy = {
  en: {
    nav: {
      how: "How it works",
      features: "Features",
      pricing: "Pricing",
      signIn: "Sign in",
      getStarted: "Get started →",
      menu: {
        open: "Open menu",
        close: "Close menu",
        drawerTitle: "Menu",
        explore: "Explore",
        settings: "Appearance & language",
      },
    },
    announce: {
      pre: "Free Trial",
      msg: "20 credits to launch your first WhatsApp campaign — no credit card required",
      cta: "Claim now →",
    },
    hero: {
      badge: "WhatsApp-native B2B outreach",
      h1a: "Turn any city",
      h1Line2Prefix: "into a ",
      h1b: "pipeline",
      h1c: "of",
      h1d: "clients",
      p: "Find verified businesses on Google Places, reach them on WhatsApp with personalized campaigns, and handle replies as a team — one dashboard.",
      heroCta: "Get started — 20 credits",
      watchDemo: "See how it works ↓",
      emailPlaceholder: "you@company.com",
      microcopy: "No credit card · Setup in 2 minutes · Cancel anytime",
      trust: ["Open rate", "vs email", "To launch"],
    },
    socialProof: {
      pre: "Trusted by",
      tagline: "200+ growth teams in MENA & EU",
      counters: [
        { v: "1.2M+", l: "messages sent" },
        { v: "78K", l: "leads extracted this week" },
        { v: "94%", l: "delivery rate" },
        { v: "4.8/5", l: "average rating" },
      ],
    },
    caseStudy: {
      lbl: "Customer story",
      kicker: "B2B growth agency · Greater Tunis",
      headline: "47 WhatsApp replies in under 24 hours",
      quote:
        "We sent 800 personalized WhatsApp messages to local restaurants on Monday. By Tuesday afternoon we had 47 replies and three new catering contracts.",
      role: "— Digital marketing lead, Tunis",
    },
    comparison: {
      lbl: "Why WhispFlow",
      h2a: "Cold email is dead.",
      h2b: "WhatsApp wins.",
      headers: ["", "Cold email", "LinkedIn DM", "WhispFlow"],
      rows: [
        { metric: "Open / read rate",     a: "~20%",        b: "~30%",         c: "98%" },
        { metric: "Average reply rate",   a: "1–3%",        b: "5%",           c: "15–25%" },
        { metric: "Time to first send",   a: "2–4 hours",   b: "1 hour",       c: "2 minutes" },
        { metric: "Lead source included", a: "❌ buy a list", b: "❌ gather manually", c: "✓ built-in extraction" },
        { metric: "Personalization",      a: "Templates",   b: "Manual",       c: "{{tokens}} + media" },
        { metric: "Account safety",       a: "Spam folder", b: "InMail limits", c: "Smart rate-limit" },
      ],
      footnote: "Sources: HubSpot 2024, LinkedIn Sales report, internal data.",
    },
    faq: {
      lbl: "FAQ",
      h2: "Honest answers.",
      items: [
        { q: "Will my WhatsApp number get banned?",
          a: "No — WhispFlow uses smart rate-limiting, session warmup, randomized delays and opt-out blacklists exactly the way Meta recommends. We also let you connect multiple numbers and rotate sends. Across 1.2M+ messages our user ban rate is under 0.3%." },
        { q: "Is extracting leads from Google Places legal?",
          a: "We only collect publicly-listed business contacts — the same data you'd find by searching each business one by one. We never touch private profiles. You're responsible for complying with local outreach laws (we provide built-in opt-out handling)." },
        { q: "How does the 20-credit Free Trial work?",
          a: "Sign up with email or Google — no card. You instantly get 20 credits, which equals 20 lead extractions OR 40 messages OR any mix. Use them however you want, no time limit. Upgrade only when you're ready." },
        { q: "What is a 'credit'?",
          a: "1 extracted phone-verified lead = 1 credit. 1 sent WhatsApp message = 0.5 credit. So a Basic pack of 1,500 credits gets you up to 1,500 leads or 3,000 messages." },
        { q: "Can I cancel or get a refund?",
          a: "Yes. Plans renew monthly and you can cancel anytime in your dashboard. We also offer a 7-day money-back guarantee on your first paid pack — no questions asked." },
        { q: "Do you support multiple WhatsApp numbers / team members?",
          a: "Yes. Pro supports up to 3 connected numbers; Enterprise is unlimited. Every plan includes a shared team inbox so multiple teammates can answer replies." },
        { q: "What countries / languages does it support?",
          a: "Anywhere with WhatsApp coverage (190+ countries). The platform UI ships in English, French, Arabic and Italian — and your campaign messages can be in any language you write them in." },
        { q: "How do I migrate my existing leads?",
          a: "Import a CSV with phone numbers in any common format. We deduplicate, validate against WhatsApp, and you're ready to send in under a minute." },
      ],
    },
    stickyCta: {
      msg: "Free Trial: 20 credits, no card",
      btn: "Start free →",
    },
    phone: {
      chip: ["Delivered", "Replied", "Hot leads"],
      online: "online now",
      m1: "Hi Karim! We help restaurants in Tunis get more clients via WhatsApp. Interested?",
      m2: "Yes please, how does it work?",
      m3: "I'll send you a quick demo 🚀",
      m4: "Perfect, send it over!",
    },
    problem: {
      lbl1: "The problem",
      h2a: "Cold outreach",
      h2MidGlue: " is ",
      h2b: "broken.",
      body: "Email sits at 20% open rate. LinkedIn is saturated. Cold calls are ignored. Meanwhile WhatsApp messages are read by 98% of people — usually within minutes of receiving them.",
      bad: [
        "Hours spent manually hunting for leads",
        "One-by-one sending with zero automation",
        "No idea who read or ignored your message",
        "WhatsApp bans from clumsy bulk sending",
      ],
      lbl2: "The fix",
      fixH2a: "WhispFlow",
      fixH2b: "solves all of it.",
      fixVerb: "solves",
      fixTail: "all of it.",
      fixBody: "One platform that finds your leads, confirms they're active on WhatsApp, sends personalized campaigns at scale, and brings every reply into a single team inbox.",
      good: [
        "1,000 verified contacts in under 5 minutes",
        "Campaigns launched with 2 clicks",
        "Read & reply rates visible in real time",
        "Smart rate limiting protects your accounts",
      ],
    },
    how: {
      lbl: "Process",
      h2a: "Zero to 1,000",
      h2bBefore: "conversations",
      h2bEm: "today.",
      steps: [
        { t: "Extract your leads", d: "Pick any city and industry. We pull business name, phone, category, rating and address from Google Places. Thousands of contacts in minutes." },
        { t: "Validate & segment", d: "Every number is checked against WhatsApp before launch. Filter by industry, city or size. Zero credits wasted on dead numbers." },
        { t: "Send your campaign", d: "Personalize with tokens. Attach images or PDFs. Schedule for the right moment. Our engine handles delivery, rotation and limits." },
        { t: "Close from your inbox", d: "Every reply lands in your shared team inbox. See who is interested in real time, assign conversations, and close deals fast." },
      ],
    },
    numbers: {
      lbl: "Why WhatsApp",
      h2a: "The channel",
      h2bThat: "that",
      h2bEm: "converts.",
      h2bAr: "",
      nb: "of WhatsApp messages are opened — compared to just 20% for email. It is the highest-engagement outreach channel available to B2B businesses today.",
      ns1: "more replies than cold email targeting the same audience",
      ns2: "from signup to first campaign sent on WhispFlow",
    },
    features: {
      lbl: "Platform",
      h2a: "Built for",
      h2em: "serious",
      h2rest: "outreach.",
      h2ar: "",
      items: [
        { t: "Places extraction", d: "Extract business name, phone, category and city from any location on earth via Google Places. Thousands of verified leads in minutes, not days of manual research." },
        { t: "WA number validator", d: "Every number confirmed active on WhatsApp before your campaign fires. No bounced sends, no wasted credits, no account health damaged by dead numbers." },
        { t: "Campaign builder", d: "Personalize with {{name}}, {{city}}, {{business}}. Attach images, menus, PDFs. A/B test two variants with automatic winner selection." },
        { t: "Live analytics", d: "Real-time delivery, read, and reply rates. Campaign score grades your outreach instantly so you know what to improve next time." },
        { t: "Shared inbox", d: "All replies in one team inbox. Assign conversations to teammates, write auto-replies for common questions, and close hot leads before they go cold." },
        { t: "Account protection", d: "Automatic rate limits, session warmup, opt-out blacklists, and multi-session rotation keep every WhatsApp account healthy and active long term." },
      ],
      analyticsCard: {
        title: "Restaurants — Tunis",
        delivered: "Delivered",
        read: "Read",
        replied: "Replied",
        optouts: "Opt-outs",
        tags: ["847 sent", "185 replies", "avg 8 min read"],
      },
    },
    pricing: {
      lbl: "Pricing",
      h2a: "Pay only for",
      h2em: "what you send.",
      h2rest: "",
      monthlyPlansTitle: "Monthly plans",
      tierPopular: "Popular",
      tierPerMonth: "/ month",
      tierCta: "Get started",
    },
    proof: {
      lbl: "Results",
      h2a: "Real businesses,",
      h2em: "real",
      h2rest: "outcomes.",
      h2arPrefix: "",
      h2arEm: "",
      q1: "We sent 800 messages to restaurant owners in Tunis on Monday morning. By Tuesday we had 47 replies and closed 3 new contracts. The ROI was immediate.",
      q2: "I used to spend hours messaging potential clients one by one. WhispFlow does it in minutes and shows me exactly who is interested before I pick up the phone.",
      role1: "Digital marketing agency, Tunis",
      role2: "B2B software reseller, Sfax",
    },
    cta: {
      lbl: "Start today",
      h2a: "Your next",
      h2em: "1,000",
      h2rest: "clients are waiting.",
      p: "Stop emailing into the void. WhatsApp is where business gets done — and WhispFlow gets you there in minutes.",
      btn: "Launch your first campaign",
      note: "NO CREDIT CARD · FREE PLAN · SETUP IN 2 MINUTES",
    },
    footer: {
      privacy: "Privacy",
      terms: "Terms",
      contact: "Contact",
      copy: "© 2026 WhispFlow",
    },
  },
  ar: {
    nav: {
      how: "كيف يعمل",
      features: "المميزات",
      pricing: "الأسعار",
      signIn: "تسجيل الدخول",
      getStarted: "ابدأ الآن →",
      menu: {
        open: "فتح القائمة",
        close: "إغلاق القائمة",
        drawerTitle: "القائمة",
        explore: "استكشف",
        settings: "المظهر واللغة",
      },
    },
    announce: {
      pre: "تجربة مجانية",
      msg: "20 رصيداً لإطلاق أول حملة واتساب — بدون بطاقة ائتمان",
      cta: "احصل عليها الآن →",
    },
    hero: {
      badge: "تواصل B2B عبر واتساب",
      h1a: "حوّل أي مدينة",
      h1Line2Prefix: "إلى ",
      h1b: "خط عملاء",
      h1c: "من",
      h1d: "العملاء",
      p: "اعثر على أعمال موثقة من Google Places، وتواصل معها عبر واتساب بحملات مخصصة، وأدر الردود كفريق — من لوحة واحدة.",
      heroCta: "ابدأ الآن — 20 رصيداً",
      watchDemo: "شاهد كيف يعمل ↓",
      emailPlaceholder: "بريدك@الشركة.com",
      microcopy: "بدون بطاقة · جاهز في دقيقتين · إلغاء في أي وقت",
      trust: ["معدل الفتح", "مقارنة بالبريد الإلكتروني", "جاهز في دقيقتين"],
    },
    socialProof: {
      pre: "يستخدمها",
      tagline: "+200 فريق نمو في منطقة الشرق الأوسط وأوروبا",
      counters: [
        { v: "+1.2M", l: "رسالة مرسلة" },
        { v: "78K", l: "عميل تم استخراجه هذا الأسبوع" },
        { v: "94%", l: "معدل التسليم" },
        { v: "4.8/5", l: "متوسط التقييم" },
      ],
    },
    caseStudy: {
      lbl: "قصة عميل",
      kicker: "وكالة نمو B2B · تونس الكبرى",
      headline: "47 رداً على واتساب في أقل من 24 ساعة",
      quote:
        "أرسلنا 800 رسالة واتساب مخصصة لمطاعم محلية يوم الاثنين. بحلول بعد ظهر الثلاثاء كان لدينا 47 رداً وثلاثة عقود تموين جديدة.",
      role: "— مسؤول تسويق رقمي، تونس",
    },
    comparison: {
      lbl: "لماذا WhispFlow",
      h2a: "البريد البارد لم يعد فعالاً.",
      h2b: "واتساب يربح.",
      headers: ["", "بريد بارد", "رسائل لينكدإن", "WhispFlow"],
      rows: [
        { metric: "معدل الفتح", a: "~20%", b: "~30%", c: "98%" },
        { metric: "متوسط الرد", a: "1–3%", b: "5%", c: "15–25%" },
        { metric: "وقت أول إرسال", a: "2–4 ساعات", b: "ساعة", c: "دقيقتان" },
        { metric: "مصدر العملاء", a: "❌ شراء قائمة", b: "❌ بحث يدوي", c: "✓ مدمج" },
        { metric: "التخصيص", a: "قوالب", b: "يدوي", c: "{{رموز}} + وسائط" },
        { metric: "أمان الحساب", a: "خانة الرسائل المزعجة", b: "حدود InMail", c: "حد ذكي" },
      ],
      footnote: "المصادر: HubSpot 2024، تقرير LinkedIn Sales، بيانات داخلية.",
    },
    faq: {
      lbl: "الأسئلة الشائعة",
      h2: "إجابات صريحة.",
      items: [
        { q: "هل سيتم حظر رقم واتساب الخاص بي؟",
          a: "لا — تستخدم WhispFlow حدوداً ذكية للإرسال وإحماءً للجلسات وتأخيرات عشوائية وقوائم إلغاء اشتراك تماماً كما توصي به Meta. كما يمكنك ربط أرقام متعددة وتدويرها. عبر أكثر من 1.2 مليون رسالة، نسبة الحظر لمستخدمينا أقل من 0.3٪." },
        { q: "هل استخراج العملاء من محركات البحث قانوني؟",
          a: "نجمع فقط جهات اتصال أعمال منشورة علنياً — نفس البيانات التي ستجدها بالبحث عن كل نشاط على Google. لا نلمس الملفات الخاصة. أنت مسؤول عن الالتزام بقوانين التواصل المحلية (نوفر إدارة مدمجة لإلغاء الاشتراك)." },
        { q: "كيف تعمل التجربة المجانية بـ 20 رصيداً؟",
          a: "سجّل عبر البريد أو Google — بدون بطاقة. تحصل فوراً على 20 رصيداً، تساوي 20 استخراج عميل أو 40 رسالة أو أي مزيج. استخدمها كما تشاء، بلا حد زمني. الترقية فقط عند جاهزيتك." },
        { q: "ما هو 'الرصيد'؟",
          a: "عميل واحد مستخرج برقم موثق = رصيد واحد. رسالة واتساب واحدة = 0.5 رصيد. لذا حزمة Basic بـ 1500 رصيد تتيح لك ما يصل إلى 1500 عميل أو 3000 رسالة." },
        { q: "هل يمكنني الإلغاء أو استرداد المبلغ؟",
          a: "نعم. الخطط تتجدد شهرياً ويمكنك الإلغاء في أي وقت من لوحة التحكم. نقدم أيضاً ضمان استرداد 7 أيام على أول حزمة مدفوعة — بدون أسئلة." },
        { q: "هل يدعم أرقام واتساب وأعضاء فريق متعددين؟",
          a: "نعم. Pro يدعم حتى 3 أرقام موصولة؛ Enterprise بلا حدود. كل خطة تتضمن صندوق وارد مشترك للفريق." },
        { q: "ما هي الدول واللغات المدعومة؟",
          a: "أينما يتوفر واتساب (+190 دولة). واجهة المنصة بالإنجليزية والفرنسية والعربية والإيطالية — رسائلك يمكن أن تكون بأي لغة." },
        { q: "كيف أنقل عملائي الحاليين؟",
          a: "استورد ملف CSV يحتوي على أرقام الهواتف بأي تنسيق شائع. نقوم بإزالة المكررات والتحقق من واتساب، وتكون جاهزاً للإرسال خلال أقل من دقيقة." },
      ],
    },
    stickyCta: {
      msg: "تجربة مجانية: 20 رصيداً، بدون بطاقة",
      btn: "ابدأ مجاناً →",
    },
    phone: {
      chip: ["تم التسليم", "الردود", "عملاء محتملون"],
      online: "متصل الآن",
      m1: "مرحباً كريم! نساعد المطاعم في تونس على جذب المزيد من العملاء عبر واتساب. هل تهتم؟",
      m2: "بالطبع، كيف يعمل؟",
      m3: "سأرسل لك عرضاً سريعاً 🚀",
      m4: "ممتاز، أرسله إليّ.",
    },
    problem: {
      lbl1: "المشكلة",
      h2a: "التواصل البارد",
      h2MidGlue: "",
      h2b: "لم يعد يجدي نفعاً.",
      body: "البريد الإلكتروني لا يُفتح إلا بنسبة 20%. لينكدإن مشبع. المكالمات الباردة تُتجاهل. في المقابل، تُقرأ رسائل واتساب من قبل 98% من الناس — عادةً في غضون دقائق.",
      bad: [
        "ساعات تُضيَّع في البحث اليدوي عن العملاء",
        "الإرسال واحداً تلو الآخر دون أتمتة",
        "لا فكرة عمّن قرأ رسالتك أو تجاهلها",
        "حظر واتساب بسبب الإرسال الجماعي العشوائي",
      ],
      lbl2: "الحل",
      fixH2a: "WhispFlow",
      fixH2b: "يحل كل شيء.",
      fixVerb: "",
      fixTail: "",
      fixBody: "منصة واحدة تجد عملاءك المحتملين، وتتحقق من نشاطهم على واتساب، وترسل حملات مخصصة على نطاق واسع، وتجمع كل رد في صندوق وارد فريق واحد.",
      good: [
        "1000 جهة اتصال موثقة في أقل من 5 دقائق",
        "إطلاق الحملات بنقرتين",
        "معدلات القراءة والرد مرئية في الوقت الفعلي",
        "حد ذكي للإرسال يحمي حساباتك",
      ],
    },
    how: {
      lbl: "العملية",
      h2a: "من الصفر إلى",
      h2bBefore: "محادثة",
      h2bEm: "اليوم..",
      steps: [
        { t: "استخراج العملاء المحتملين", d: "اختر مدينة وصناعة. نستخرج اسم النشاط والهاتف والفئة والتقييم والعنوان من محركات البحث. آلاف جهات الاتصال في دقائق." },
        { t: "التحقق والتصنيف", d: "يتم التحقق من كل رقم على واتساب قبل الإطلاق. فلتر حسب الصناعة أو المدينة أو الحجم. لا تضييع للرصيد على أرقام ميتة." },
        { t: "إرسال حملتك", d: "خصص الرسائل بالرموز. أرفق صور أو ملفات PDF. حدد الوقت المناسب. محركنا يتولى التسليم والتناوب والحدود." },
        { t: "الإغلاق من صندوق الوارد", d: "يصل كل رد إلى صندوق الوارد المشترك. رؤية من هو مهتم في الوقت الفعلي، وتعيين المحادثات، وإتمام الصفقات بسرعة." },
      ],
    },
    numbers: {
      lbl: "لماذا واتساب",
      h2a: "القناة",
      h2bThat: "",
      h2bEm: "",
      h2bAr: "الأعلى تحويلاً.",
      nb: "تُفتح رسائل واتساب — مقارنةً بنحو 20% للبريد الإلكتروني. إنه القناة الأعلى تفاعلاً المتاحة لأعمال B2B اليوم.",
      ns1: "ردود أكثر مقارنةً بالبريد البارد على نفس الجمهور",
      ns2: "من التسجيل إلى أول حملة مرسلة على WhispFlow",
    },
    features: {
      lbl: "المنصة",
      h2a: "مصممة",
      h2em: "",
      h2rest: "",
      h2ar: "للتواصل الاحترافي.",
      items: [
        { t: "استخراج من محركات البحث", d: "استخرج الاسم والهاتف والفئة والمدينة من أي مكان عبر محركات البحث. آلاف العملاء الموثوقين في دقائق، لا في أيام من البحث اليدوي." },
        { t: "التحقق من أرقام واتساب", d: "كل رقم يتم تأكيد نشاطه على واتساب قبل إطلاق حملتك. لا إرساليات فاشلة ولا رصيد مهدر." },
        { t: "بناء الحملات", d: "خصص الرسائل بـ {{name}} و {{city}} و {{business}}. أرفق صوراً أو قوائم أو PDF. اختبر نسختين مع اختيار تلقائي للفائز." },
        { t: "تحليلات فورية", d: "معدلات التسليم والقراءة والرد في الوقت الفعلي. يُقيّم نظامنا حملتك فوراً." },
        { t: "صندوق وارد مشترك", d: "كل الردود في مكان واحد. عيّن المحادثات، وتلقَّ ردوداً تلقائية للأسئلة الشائعة، وأغلق الصفقات قبل أن تبرد." },
        { t: "حماية الحسابات", d: "حدود إرسال تلقائية وإحماء للجلسات وقوائم إلغاء الاشتراك وتناوب متعدد الجلسات تحافظ على صحة كل حساب واتساب على المدى البعيد." },
      ],
      analyticsCard: {
        title: "مطاعم — تونس",
        delivered: "تم التسليم",
        read: "مقروء",
        replied: "الردود",
        optouts: "إلغاء الاشتراك",
        tags: ["847 مُرسل", "185 رداً", "متوسط القراءة 8 دقائق"],
      },
    },
    pricing: {
      lbl: "الأسعار",
      h2a: "ادفع فقط",
      h2em: "ما ترسله.",
      h2rest: "",
      monthlyPlansTitle: "الخطط الشهرية",
      tierPopular: "الأكثر شيوعاً",
      tierPerMonth: "/ شهر",
      tierCta: "ابدأ الآن",
    },
    proof: {
      lbl: "النتائج",
      h2a: "أعمال حقيقية،",
      h2em: "",
      h2rest: "",
      h2arPrefix: "نتائج ",
      h2arEm: "حقيقية",
      q1: "أرسلنا 800 رسالة لأصحاب المطاعم في تونس صباح الاثنين. وبحلول الثلاثاء كان لدينا 47 رداً وأبرمنا 3 عقود جديدة. العائد كان فورياً.",
      q2: "كنت أقضي ساعات في مراسلة العملاء المحتملين واحداً تلو الآخر. WhispFlow يفعل ذلك في دقائق، ويُظهر لي من هو مهتم قبل أن أرفع الهاتف.",
      role1: "وكالة تسويق رقمي، تونس",
      role2: "موزع برامج B2B، صفاقس",
    },
    cta: {
      lbl: "ابدأ اليوم.",
      h2a: "عملاؤك الـ",
      h2em: "",
      h2rest: "المقبلون ينتظرونك.",
      p: "توقف عن إرسال رسائل بريد إلكتروني في الفراغ. واتساب هو حيث تُنجز الأعمال — وWhispFlow يوصلك إليه في دقائق.",
      btn: "أطلق حملتك الأولى",
      note: "بدون بطاقة ائتمان · خطة مجانية · الإعداد في دقيقتين",
    },
    footer: {
      privacy: "سياسة الخصوصية",
      terms: "الشروط",
      contact: "تواصل معنا",
      copy: "© 2026 WhispFlow",
    },
  },
  fr: {
    nav: {
      how: "Comment ça marche",
      features: "Fonctionnalités",
      pricing: "Tarifs",
      signIn: "Connexion",
      getStarted: "Commencer →",
      menu: {
        open: "Ouvrir le menu",
        close: "Fermer le menu",
        drawerTitle: "Menu",
        explore: "Explorer",
        settings: "Apparence et langue",
      },
    },
    announce: {
      pre: "Essai gratuit",
      msg: "20 crédits pour lancer votre première campagne WhatsApp — sans carte bancaire",
      cta: "Réclamer →",
    },
    hero: {
      badge: "Prospection B2B native WhatsApp",
      h1a: "Transformez n'importe quelle ville",
      h1Line2Prefix: "en un ",
      h1b: "pipeline",
      h1c: "de",
      h1d: "clients",
      p: "Trouvez des entreprises vérifiées sur Google Places, engagez-les sur WhatsApp avec des campagnes personnalisées et gérez les réponses en équipe — depuis un seul tableau de bord.",
      heroCta: "Commencer — 20 crédits",
      watchDemo: "Voir comment ça marche ↓",
      emailPlaceholder: "vous@entreprise.com",
      microcopy: "Sans carte · Prêt en 2 min · Annulable à tout moment",
      trust: ["Taux d'ouverture", "vs e-mail", "Prêt en 2 min"],
    },
    socialProof: {
      pre: "Adoptée par",
      tagline: "200+ équipes growth en MENA et UE",
      counters: [
        { v: "1,2M+", l: "messages envoyés" },
        { v: "78K", l: "leads extraits cette semaine" },
        { v: "94%", l: "taux de livraison" },
        { v: "4,8/5", l: "note moyenne" },
      ],
    },
    caseStudy: {
      lbl: "Témoignage client",
      kicker: "Agence de croissance B2B · Grand Tunis",
      headline: "47 réponses WhatsApp en moins de 24 h",
      quote:
        "Nous avons envoyé 800 messages WhatsApp personnalisés à des restaurants locaux lundi. Mardi après-midi, nous avions 47 réponses et trois nouveaux contrats traiteur.",
      role: "— Responsable marketing digital, Tunis",
    },
    comparison: {
      lbl: "Pourquoi WhispFlow",
      h2a: "Le cold email est mort.",
      h2b: "WhatsApp gagne.",
      headers: ["", "Cold email", "DM LinkedIn", "WhispFlow"],
      rows: [
        { metric: "Taux d'ouverture", a: "~20%", b: "~30%", c: "98%" },
        { metric: "Taux de réponse", a: "1–3%", b: "5%", c: "15–25%" },
        { metric: "Délai 1er envoi", a: "2–4 h", b: "1 h", c: "2 min" },
        { metric: "Source de leads", a: "❌ acheter une liste", b: "❌ collecte manuelle", c: "✓ extraction intégrée" },
        { metric: "Personnalisation", a: "Modèles", b: "Manuelle", c: "{{tokens}} + médias" },
        { metric: "Sécurité du compte", a: "Spam", b: "Limites InMail", c: "Limite intelligente" },
      ],
      footnote: "Sources : HubSpot 2024, rapport LinkedIn Sales, données internes.",
    },
    faq: {
      lbl: "FAQ",
      h2: "Réponses honnêtes.",
      items: [
        { q: "Mon numéro WhatsApp risque-t-il d'être banni ?",
          a: "Non — WhispFlow utilise un rate-limiting intelligent, le warm-up des sessions, des délais aléatoires et des listes opt-out conformes aux recommandations Meta. Vous pouvez aussi connecter plusieurs numéros et faire de la rotation. Sur 1,2M+ de messages, notre taux de ban utilisateur est inférieur à 0,3%." },
        { q: "L'extraction de leads via Google Places est-elle légale ?",
          a: "Nous ne collectons que des contacts professionnels publiquement listés — les mêmes données que vous trouveriez en recherchant chaque entreprise. Nous ne touchons jamais aux profils privés. Vous restez responsable du respect des lois locales (la gestion des opt-out est intégrée)." },
        { q: "Comment fonctionne l'essai gratuit de 20 crédits ?",
          a: "Inscrivez-vous par e-mail ou Google — sans carte. Vous obtenez instantanément 20 crédits = 20 leads OU 40 messages OU n'importe quel mélange. Aucune limite de temps. Mise à niveau quand vous le décidez." },
        { q: "C'est quoi un 'crédit' ?",
          a: "1 lead extrait & validé = 1 crédit. 1 message WhatsApp envoyé = 0,5 crédit. Donc un pack Basic de 1 500 crédits = jusqu'à 1 500 leads ou 3 000 messages." },
        { q: "Puis-je annuler ou être remboursé ?",
          a: "Oui. Les forfaits se renouvellent au mois et vous pouvez annuler à tout moment depuis le tableau de bord. Garantie satisfait ou remboursé 7 jours sur le 1er pack — sans question." },
        { q: "Vous gérez plusieurs numéros / coéquipiers ?",
          a: "Oui. Pro = jusqu'à 3 numéros connectés ; Enterprise = illimité. Toutes les offres incluent une boîte de réception partagée." },
        { q: "Quels pays / langues sont supportés ?",
          a: "Partout où WhatsApp est dispo (190+ pays). Interface en EN, FR, AR, IT — vos messages peuvent être dans n'importe quelle langue." },
        { q: "Comment importer mes leads existants ?",
          a: "Importez un CSV avec les numéros dans n'importe quel format courant. On déduplique, on valide sur WhatsApp, vous êtes prêt à envoyer en moins d'une minute." },
      ],
    },
    stickyCta: {
      msg: "Essai gratuit : 20 crédits, sans carte",
      btn: "Commencer gratuit →",
    },
    phone: {
      chip: ["Livré", "Réponses", "Leads chauds"],
      online: "en ligne",
      m1: "Bonjour Karim ! Nous aidons les restaurants de Tunis à attirer plus de clients via WhatsApp. Ça vous intéresse ?",
      m2: "Oui, comment ça marche ?",
      m3: "Je vous envoie une courte démo 🚀",
      m4: "Parfait, envoyez-la !",
    },
    problem: {
      lbl1: "Le problème",
      h2a: "La prospection froide",
      h2MidGlue: " est ",
      h2b: "cassée.",
      body: "L'e-mail s'ouvre à peine à 20 %. LinkedIn est saturé. Les appels à froid sont ignorés. Les messages WhatsApp sont lus par environ 98 % des destinataires — souvent en quelques minutes.",
      bad: [
        "Des heures à chercher des leads à la main",
        "Envoi un par un sans automatisation",
        "Aucune idée de qui a lu ou ignoré",
        "Risque de bannissement en masse mal géré",
      ],
      lbl2: "La solution",
      fixH2a: "WhispFlow",
      fixH2b: "résout tout cela.",
      fixVerb: "résout",
      fixTail: "tout cela.",
      fixBody: "Une plateforme qui trouve vos leads, vérifie qu'ils sont actifs sur WhatsApp, envoie des campagnes personnalisées à l'échelle et centralise chaque réponse dans une boîte d'équipe unique.",
      good: [
        "1 000 contacts vérifiés en moins de 5 minutes",
        "Campagnes lancées en 2 clics",
        "Lecture et réponses visibles en temps réel",
        "Limitation intelligente pour protéger vos comptes",
      ],
    },
    how: {
      lbl: "Processus",
      h2a: "De zéro à 1 000",
      h2bBefore: "conversations",
      h2bEm: "aujourd'hui.",
      steps: [
        { t: "Extrayez vos leads", d: "Choisissez une ville et un secteur. Nous extrayons nom, téléphone, catégorie, note et adresse depuis Google Places. Des milliers de contacts en minutes." },
        { t: "Validez et segmentez", d: "Chaque numéro est vérifié sur WhatsApp avant l'envoi. Filtrez par secteur, ville ou taille. Zéro crédit gaspillé sur des numéros morts." },
        { t: "Envoyez votre campagne", d: "Personnalisez avec des jetons. Joignez images ou PDF. Planifiez au bon moment. Notre moteur gère la livraison, la rotation et les limites." },
        { t: "Concluez depuis la boîte de réception", d: "Chaque réponse arrive dans une boîte partagée. Voyez qui est intéressé en direct, assignez les conversations et concluez vite." },
      ],
    },
    numbers: {
      lbl: "Pourquoi WhatsApp",
      h2a: "Le canal",
      h2bThat: "qui",
      h2bEm: "convertit.",
      h2bAr: "",
      nb: "des messages WhatsApp sont ouverts — contre environ 20 % pour l'e-mail. C'est l'un des canaux d'engagement les plus forts pour le B2B aujourd'hui.",
      ns1: "plus de réponses que l'e-mail froid sur le même public",
      ns2: "de l'inscription à la première campagne envoyée sur WhispFlow",
    },
    features: {
      lbl: "Plateforme",
      h2a: "Conçue pour une",
      h2em: "prospection",
      h2rest: "sérieuse.",
      h2ar: "",
      items: [
        { t: "Extraction Google Places", d: "Extrayez nom, téléphone, catégorie et ville partout dans le monde via Google Places. Des milliers de leads vérifiés en minutes, pas en jours de recherche manuelle." },
        { t: "Validateur de numéros WA", d: "Chaque numéro est confirmé actif sur WhatsApp avant l'envoi. Pas d'échecs, pas de crédits perdus, pas de santé de compte dégradée." },
        { t: "Constructeur de campagnes", d: "Personnalisez avec {{name}}, {{city}}, {{business}}. Joignez images, menus, PDF. Testez deux variantes avec sélection automatique du gagnant." },
        { t: "Analytique en direct", d: "Taux de livraison, lecture et réponse en temps réel. Un score de campagne évalue votre prospection instantanément." },
        { t: "Boîte partagée", d: "Toutes les réponses au même endroit. Assignez aux coéquipiers, réponses automatiques aux questions fréquentes, concluez avant que le lead refroidisse." },
        { t: "Protection des comptes", d: "Limites automatiques, préchauffage des sessions, listes d'exclusion et rotation multi-session pour garder chaque compte WhatsApp sain sur la durée." },
      ],
      analyticsCard: {
        title: "Restaurants — Tunis",
        delivered: "Livré",
        read: "Lu",
        replied: "Réponses",
        optouts: "Désinscriptions",
        tags: ["847 envoyés", "185 réponses", "lecture moy. 8 min"],
      },
    },
    pricing: {
      lbl: "Tarifs",
      h2a: "Payez uniquement",
      h2em: "ce que vous envoyez.",
      h2rest: "",
      monthlyPlansTitle: "Forfaits mensuels",
      tierPopular: "Populaire",
      tierPerMonth: "/ mois",
      tierCta: "Commencer",
    },
    proof: {
      lbl: "Résultats",
      h2a: "Des entreprises réelles,",
      h2em: "des",
      h2rest: "résultats réels.",
      h2arPrefix: "",
      h2arEm: "",
      q1: "Nous avons envoyé 800 messages aux restaurateurs de Tunis lundi matin. Mardi nous avions 47 réponses et 3 nouveaux contrats. Le ROI a été immédiat.",
      q2: "Avant je passais des heures à contacter les prospects un par un. WhispFlow le fait en minutes et me montre qui est intéressé avant que je décroche le téléphone.",
      role1: "Agence marketing digital, Tunis",
      role2: "Revendeur logiciel B2B, Sfax",
    },
    cta: {
      lbl: "Commencez aujourd'hui",
      h2a: "Vos prochains",
      h2em: "1 000",
      h2rest: "clients vous attendent.",
      p: "Arrêtez d'envoyer des e-mails dans le vide. WhatsApp est là où se fait l'affaire — et WhispFlow vous y met en quelques minutes.",
      btn: "Lancer votre première campagne",
      note: "SANS CARTE BANCAIRE · PLAN GRATUIT · PRÊT EN 2 MINUTES",
    },
    footer: {
      privacy: "Confidentialité",
      terms: "Conditions",
      contact: "Contact",
      copy: "© 2026 WhispFlow",
    },
  },
  it: {
    nav: {
      how: "Come funziona",
      features: "Funzionalità",
      pricing: "Prezzi",
      signIn: "Accedi",
      getStarted: "Inizia →",
      menu: {
        open: "Apri menu",
        close: "Chiudi menu",
        drawerTitle: "Menu",
        explore: "Esplora",
        settings: "Aspetto e lingua",
      },
    },
    announce: {
      pre: "Prova gratis",
      msg: "20 crediti per lanciare la tua prima campagna WhatsApp — senza carta",
      cta: "Richiedi ora →",
    },
    hero: {
      badge: "Outreach B2B nativo WhatsApp",
      h1a: "Trasforma qualsiasi città",
      h1Line2Prefix: "in un ",
      h1b: "pipeline",
      h1c: "di",
      h1d: "clienti",
      p: "Trova attività verificate su Google Places, raggiungile su WhatsApp con campagne personalizzate e gestisci le risposte in team — da un’unica dashboard.",
      heroCta: "Inizia — 20 crediti",
      watchDemo: "Vedi come funziona ↓",
      emailPlaceholder: "tu@azienda.com",
      microcopy: "Senza carta · Pronto in 2 min · Annullabile sempre",
      trust: ["Tasso di apertura", "vs email", "Pronto in 2 min"],
    },
    socialProof: {
      pre: "Usato da",
      tagline: "200+ team growth in MENA e UE",
      counters: [
        { v: "1,2M+", l: "messaggi inviati" },
        { v: "78K", l: "lead estratti questa settimana" },
        { v: "94%", l: "tasso consegna" },
        { v: "4,8/5", l: "valutazione media" },
      ],
    },
    caseStudy: {
      lbl: "Storia cliente",
      kicker: "Agenzia growth B2B · Grande Tunisi",
      headline: "47 risposte WhatsApp in meno di 24 ore",
      quote:
        "Lunedì abbiamo inviato 800 messaggi WhatsApp personalizzati a ristoranti locali. Martedì pomeriggio avevamo 47 risposte e tre nuovi contratti catering.",
      role: "— Lead marketing digitale, Tunisi",
    },
    comparison: {
      lbl: "Perché WhispFlow",
      h2a: "La cold email è morta.",
      h2b: "WhatsApp vince.",
      headers: ["", "Cold email", "DM LinkedIn", "WhispFlow"],
      rows: [
        { metric: "Tasso di apertura", a: "~20%", b: "~30%", c: "98%" },
        { metric: "Tasso di risposta", a: "1–3%", b: "5%", c: "15–25%" },
        { metric: "Tempo al 1° invio", a: "2–4 ore", b: "1 ora", c: "2 minuti" },
        { metric: "Sorgente lead", a: "❌ comprare lista", b: "❌ raccolta manuale", c: "✓ estrazione integrata" },
        { metric: "Personalizzazione", a: "Template", b: "Manuale", c: "{{token}} + media" },
        { metric: "Sicurezza account", a: "Spam folder", b: "Limiti InMail", c: "Rate-limit smart" },
      ],
      footnote: "Fonti: HubSpot 2024, report LinkedIn Sales, dati interni.",
    },
    faq: {
      lbl: "FAQ",
      h2: "Risposte oneste.",
      items: [
        { q: "Il mio numero WhatsApp rischia il ban?",
          a: "No — WhispFlow usa rate-limiting smart, warm-up sessioni, ritardi randomizzati e blacklist opt-out come consiglia Meta. Puoi anche collegare più numeri e ruotare gli invii. Su 1,2M+ messaggi il nostro tasso di ban è inferiore allo 0,3%." },
        { q: "L'estrazione di lead da Google Places è legale?",
          a: "Raccogliamo solo contatti aziendali pubblicamente elencati — gli stessi dati che troveresti cercando ogni azienda. Non tocchiamo mai i profili privati. Sei responsabile del rispetto delle leggi locali (gestione opt-out integrata)." },
        { q: "Come funziona la prova gratis con 20 crediti?",
          a: "Registrati con email o Google — senza carta. Ottieni subito 20 crediti = 20 lead estratti OPPURE 40 messaggi OPPURE qualsiasi mix. Nessun limite di tempo. Aggiorni quando vuoi." },
        { q: "Cos'è un 'credito'?",
          a: "1 lead estratto e verificato = 1 credito. 1 messaggio WhatsApp inviato = 0,5 crediti. Quindi un pacchetto Basic da 1.500 crediti = fino a 1.500 lead o 3.000 messaggi." },
        { q: "Posso annullare o farmi rimborsare?",
          a: "Sì. I piani si rinnovano mensilmente e puoi annullare in qualsiasi momento dalla dashboard. Garanzia soddisfatti o rimborsati 7 giorni sul primo pacchetto — senza domande." },
        { q: "Supportate più numeri / membri del team?",
          a: "Sì. Pro = fino a 3 numeri collegati; Enterprise = illimitati. Tutti i piani includono una inbox di team condivisa." },
        { q: "Quali paesi / lingue supportate?",
          a: "Ovunque WhatsApp sia disponibile (190+ paesi). Interfaccia in EN, FR, AR, IT — i messaggi puoi scriverli in qualsiasi lingua." },
        { q: "Come importo i lead esistenti?",
          a: "Importa un CSV con i numeri in qualsiasi formato comune. Deduplichiamo, validiamo su WhatsApp, sei pronto a inviare in meno di un minuto." },
      ],
    },
    stickyCta: {
      msg: "Prova gratis: 20 crediti, senza carta",
      btn: "Inizia gratis →",
    },
    phone: {
      chip: ["Consegnati", "Risposte", "Lead caldi"],
      online: "online ora",
      m1: "Ciao Karim! Aiutiamo i ristoranti di Tunisi ad acquisire clienti via WhatsApp. Ti interessa?",
      m2: "Sì, come funziona?",
      m3: "Ti mando una demo veloce 🚀",
      m4: "Perfetto, mandala!",
    },
    problem: {
      lbl1: "Il problema",
      h2a: "Il cold outreach",
      h2MidGlue: " è ",
      h2b: "rotto.",
      body: "L'email ha circa il 20% di aperture. LinkedIn è saturo. Le chiamate a freddo vengono ignorate. I messaggi WhatsApp vengono letti dal 98% delle persone — spesso entro pochi minuti.",
      bad: [
        "Ore spese a cercare lead a mano",
        "Invio uno a uno senza automazione",
        "Nessuna idea di chi ha letto o ignorato",
        "Ban WhatsApp per invii massivi mal gestiti",
      ],
      lbl2: "La soluzione",
      fixH2a: "WhispFlow",
      fixH2b: "risolve tutto.",
      fixVerb: "risolve",
      fixTail: "tutto.",
      fixBody: "Una piattaforma che trova i lead, verifica che siano attivi su WhatsApp, invia campagne personalizzate su larga scala e raccoglie ogni risposta in un'unica inbox di team.",
      good: [
        "1.000 contatti verificati in meno di 5 minuti",
        "Campagne avviate in 2 clic",
        "Letture e risposte visibili in tempo reale",
        "Limiti intelligenti per proteggere gli account",
      ],
    },
    how: {
      lbl: "Processo",
      h2a: "Da zero a 1.000",
      h2bBefore: "conversazioni",
      h2bEm: "oggi.",
      steps: [
        { t: "Estrai i lead", d: "Scegli città e settore. Estraiamo nome, telefono, categoria, valutazione e indirizzo da Google Places — migliaia di contatti in minuti." },
        { t: "Valida e segmenta", d: "Ogni numero è controllato su WhatsApp prima dell'invio. Filtra per settore, città o dimensione. Zero crediti sprecati su numeri morti." },
        { t: "Invia la campagna", d: "Personalizza con token. Allega immagini o PDF. Pianifica il momento giusto. Il nostro motore gestisce consegna, rotazione e limiti." },
        { t: "Chiudi dalla inbox", d: "Ogni risposta arriva nell'inbox condivisa. Vedi chi è interessato in tempo reale, assegna le conversazioni e chiudi velocemente." },
      ],
    },
    numbers: {
      lbl: "Perché WhatsApp",
      h2a: "Il canale",
      h2bThat: "che",
      h2bEm: "converte.",
      h2bAr: "",
      nb: "dei messaggi WhatsApp viene aperto — contro circa il 20% dell'email. È uno dei canali di outreach B2B con il più alto coinvolgimento.",
      ns1: "più risposte rispetto alla cold email sullo stesso pubblico",
      ns2: "dalla registrazione alla prima campagna inviata su WhispFlow",
    },
    features: {
      lbl: "Piattaforma",
      h2a: "Progettata per",
      h2em: "outreach",
      h2rest: "serio.",
      h2ar: "",
      items: [
        { t: "Estrazione Google Places", d: "Estrai nome, telefono, categoria e città da qualsiasi luogo tramite Google Places. Migliaia di lead verificati in minuti, non giorni di ricerca manuale." },
        { t: "Validatore numeri WA", d: "Ogni numero è confermato attivo su WhatsApp prima dell'invio. Nessun bounce, crediti sprecati o salute account danneggiata." },
        { t: "Builder campagne", d: "Personalizza con {{name}}, {{city}}, {{business}}. Allega immagini, menu, PDF. Test A/B con scelta automatica del vincitore." },
        { t: "Analisi live", d: "Tassi di consegna, lettura e risposta in tempo reale. Un punteggio campagna valuta subito la tua outreach." },
        { t: "Inbox condivisa", d: "Tutte le risposte in un'unica inbox di team. Assegna ai colleghi, risposte automatiche alle domande frequenti, chiudi i lead caldi prima che si raffreddino." },
        { t: "Protezione account", d: "Limiti automatici, warm-up sessioni, liste opt-out e rotazione multi-sessione per mantenere ogni account WhatsApp sano nel tempo." },
      ],
      analyticsCard: {
        title: "Ristoranti — Tunisi",
        delivered: "Consegnati",
        read: "Letti",
        replied: "Risposte",
        optouts: "Opt-out",
        tags: ["847 inviati", "185 risposte", "media lettura 8 min"],
      },
    },
    pricing: {
      lbl: "Prezzi",
      h2a: "Paga solo",
      h2em: "ciò che invii.",
      h2rest: "",
      monthlyPlansTitle: "Piani mensili",
      tierPopular: "Consigliato",
      tierPerMonth: "/ mese",
      tierCta: "Inizia",
    },
    proof: {
      lbl: "Risultati",
      h2a: "Aziende reali,",
      h2em: "risultati",
      h2rest: "reali.",
      h2arPrefix: "",
      h2arEm: "",
      q1: "Abbiamo inviato 800 messaggi ai titolari di ristoranti a Tunisi lunedì mattina. Martedì avevamo 47 risposte e 3 nuovi contratti. Il ROI è stato immediato.",
      q2: "Prima passavo ore a scrivere ai potenziali clienti uno a uno. WhispFlow lo fa in minuti e mi mostra chi è interessato prima che chiami.",
      role1: "Agenzia di marketing digitale, Tunisi",
      role2: "Rivenditore software B2B, Sfax",
    },
    cta: {
      lbl: "Inizia oggi",
      h2a: "I tuoi prossimi",
      h2em: "1.000",
      h2rest: "clienti ti aspettano.",
      p: "Smetti di mandare email nel vuoto. WhatsApp è dove si fa business — e WhispFlow ti ci porta in pochi minuti.",
      btn: "Lancia la prima campagna",
      note: "NESSUNA CARTA · PIANO GRATUITO · PRONTO IN 2 MINUTI",
    },
    footer: {
      privacy: "Privacy",
      terms: "Termini",
      contact: "Contatti",
      copy: "© 2026 WhispFlow",
    },
  },
};
